kind: Grain
version: 1.0
metadata:
  name: ansible_upload_file
  description: "Ansible grain to create and upload HTML file to S3"
spec:
  type: ansible
  playbook: playbook.yml
  inputs:
    - name: s3_bucket_name
      type: string
    - name: aws_region
      type: string
  outputs:
    - name: html_file_url
      type: string
      value: "https://{{ s3_bucket_name }}.s3.{{ aws_region }}.amazonaws.com/index.html"
